spring.application.name=poll-api
# === SERVER CONFIG ===
server.port=8080

# === H2 DATABASE ===
spring.datasource.url=jdbc:h2:mem:pollingdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# === JPA CONFIG ===
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# === LOGGING ===
logging.level.org.springframework=INFO
logging.level.com.example=DEBUG

# === SWAGGER / OPENAPI ===
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# === SECRET KEY ===
jwt.secret=my_super_secret_key_which_is_long_enough